import DragNDrop from './modules/drag-n-drop'
import GetFormInfo from './modules/getFormInfo'
import CreateCompany from './modules/create-company'
import CreatePeople from './modules/create-people'
import EditCompany from './modules/editCompany'
import DeleteItem from './modules/deleteItem'